apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-server
  template:
    metadata:
      labels:
        app: kubernetes-server
    spec:
      containers:
        - name: kubernetes-server
          image: dpuertamartos/project_kubernetes_server