apiVersion: v1
kind: Secret
metadata:
    name: kubernetes-server-secret
data:
    PORT: ENC[AES256_GCM,data:0CFKhA16y/8=,iv:wTz0tyt0PaqNCSzqJyzIy1KQG1Jm95EMKlrdTp1RcLw=,tag:PiRmBc+x7B2M5CDjxhG4xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dyu8ygjzyew4kvyn4zz9slr3tm5wq4cxvnszhc54ljjc2880npgs9u8xau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka3ZoYnl4ZmE1NG1RU1B0
            Sk5VT1Q1TWJZcmZSUGVScXlETTZlNFJaSjFzClp4TnV1ajdxUW4wTHJRMGhZVzB4
            K0o2Rm9QblZJTDFxUWVmMEVuUzNwNDQKLS0tIDlLRXhadEg2azV4bjRXMldrR1hW
            N2xUOGI5SG00UFAwNDhqazdsdDJZOTAKs4x8XTSi7k7ERdAi04BQbgmYVzPK2esD
            xN3x05A+4WrBsuoCV1GpFJn67mxCMBKY1+dMrvceCp5buutZfEriyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T09:46:17Z"
    mac: ENC[AES256_GCM,data:47Yx9DMfzZTDd75XokkZ/vzMTveKQHZ8fghaqXelFgp0Ua17j9sZ7VCSFfBeijpBUwKfzBspBZvML9zwDTZclV+2SQ50YB9hM8jmYg7Uj8dK90MbtQPf9POCjj9bKtxa8ApJ8VBEQXb6ER1HjdviN/s2/l2Htpw9f/VWrAH5fpM=,iv:WWKHusa6KP9wXYAT4gWDLNO9DdeCVGQWfgwgHFGXnbo=,tag:RAYdSGflTIusTpMRPSj04w==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.1
