apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc-load-balancer
  namespace: string-ns
spec:
  type: LoadBalancer # This should be the only unfamiliar part
  selector:
    app: flask-app-string-generator
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000